class Category {
  static final List<String> categories = [
    "Appetizers & Snacks",
    "Soups & Stews",
    "Salads & Dressings",
    "Main Dishes",
    "Pasta & Noodles",
    "Rice & Grains",
    "Vegetarian & Vegan",
    "Seafood",
    "Poultry",
    "Beef & Lamb",
    "Pork",
    "Breakfast & Brunch",
    "Sandwiches & Wraps",
    "Desserts & Sweets",
    "Baking & Pastries",
    "Beverages & Cocktails",
    "Condiments & Sauces",
    "Slow Cooker & Instant Pot",
    "Gluten-Free",
    "Dairy-Free",
    "Low-Carb",
    "Keto-Friendly",
    "Mediterranean",
    "Asian-Inspired",
    "Mexican & Tex-Mex",
    "Indian & South Asian",
    "Middle Eastern",
    "Comfort Foods",
    "Healthy & Light",
    "Holiday & Special Occasion"
  ];
}
