// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDICLyrOeX-dMcxYXkXGdoBHxYW8IuA5kg',
    appId: '1:393971147594:web:f2de81ee8d61755c07d7b3',
    messagingSenderId: '393971147594',
    projectId: 'recipe-data-6fb47',
    authDomain: 'recipe-data-6fb47.firebaseapp.com',
    storageBucket: 'recipe-data-6fb47.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3Lqf07pGy3LBLqEpADrIC2vn9EweKCRc',
    appId: '1:393971147594:android:28895f98898fee5007d7b3',
    messagingSenderId: '393971147594',
    projectId: 'recipe-data-6fb47',
    storageBucket: 'recipe-data-6fb47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmq3IrtcWDl3rAopIHBxBfX-dAbCjaZ84',
    appId: '1:393971147594:ios:99c98351dccf3a5c07d7b3',
    messagingSenderId: '393971147594',
    projectId: 'recipe-data-6fb47',
    storageBucket: 'recipe-data-6fb47.appspot.com',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmq3IrtcWDl3rAopIHBxBfX-dAbCjaZ84',
    appId: '1:393971147594:ios:0062eff54132de0f07d7b3',
    messagingSenderId: '393971147594',
    projectId: 'recipe-data-6fb47',
    storageBucket: 'recipe-data-6fb47.appspot.com',
    iosBundleId: 'com.example.recipeApp.RunnerTests',
  );
}
